<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>AzimuthStonecutterBronze</AssemblyName>
    <RootNamespace>AzimuthGaming.StonecutterBronze</RootNamespace>
    <Version>1.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx"><HintPath>../refs/core/core/BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>../refs/core/core/0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Jotunn"><HintPath>../refs/jotunn/ValheimModding-Jotunn/Jotunn.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="assembly_valheim"><HintPath>../refs/managed/Managed/assembly_valheim.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>../refs/managed/Managed/UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>../refs/managed/Managed/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
